"""
Batch 4: auto-generated by run_cycle.py.
"""

COMBOS = [
    ('Boston Terrier Mom', 'Trauma Nurse', 'black_shirt', 'dog', 'her', 'boston_terrier_mom_trauma_nurse'),
    ('Dalmatian Dad', 'Recovery Nurse', 'white_shirt', 'dog', 'his', 'dalmatian_dad_recovery_nurse'),
    ('Basset Hound Mom', 'Case Manager Nurse', 'black_shirt', 'dog', 'her', 'basset_hound_mom_case_manager_nurse'),
]
