"""
Batch 5: auto-generated by run_cycle.py.
"""

COMBOS = [
    ('Bloodhound Dad', 'Nurse Educator', 'white_shirt', 'dog', 'his', 'bloodhound_dad_nurse_educator'),
    ('Akita Mom', 'Wound Care Nurse', 'black_shirt', 'dog', 'her', 'akita_mom_wound_care_nurse'),
    ('Samoyed Dad', 'Telemetry Nurse', 'white_shirt', 'dog', 'his', 'samoyed_dad_telemetry_nurse'),
    ('Malamute Mom', 'Infusion Nurse', 'black_shirt', 'dog', 'her', 'malamute_mom_infusion_nurse'),
    ('Papillon Dad', 'Occupational Health Nurse', 'white_shirt', 'dog', 'his', 'papillon_dad_occupational_health_nurse'),
    ('Havanese Mom', 'Nurse Manager', 'black_shirt', 'dog', 'her', 'havanese_mom_nurse_manager'),
    ('Bichon Frise Dad', 'Ambulatory Care Nurse', 'white_shirt', 'dog', 'his', 'bichon_frise_dad_ambulatory_care_nurse'),
    ('Maltese Mom', 'Correctional Nurse', 'black_shirt', 'dog', 'her', 'maltese_mom_correctional_nurse'),
    ('Pug Dad', 'Labor Nurse', 'white_shirt', 'dog', 'his', 'pug_dad_labor_nurse'),
    ('English Bulldog Mom', 'Neonatal Nurse', 'black_shirt', 'dog', 'her', 'english_bulldog_mom_neonatal_nurse'),
    ('Rhodesian Ridgeback Dad', 'Nurse Life', 'white_shirt', 'dog', 'his', 'rhodesian_ridgeback_dad_nurse_life'),
    ('Chow Chow Mom', 'ICU Nurse', 'black_shirt', 'dog', 'her', 'chow_chow_mom_icu_nurse'),
]
