"""
Batch 6: auto-generated by run_cycle.py.
"""

COMBOS = [
    ('Collie Dad', 'ER Nurse', 'white_shirt', 'dog', 'his', 'collie_dad_er_nurse'),
    ('Sheltie Mom', 'School Nurse', 'black_shirt', 'dog', 'her', 'sheltie_mom_school_nurse'),
    ('Whippet Dad', 'RN Life', 'white_shirt', 'dog', 'his', 'whippet_dad_rn_life'),
    ('Greyhound Mom', 'Trauma Nurse', 'black_shirt', 'dog', 'her', 'greyhound_mom_trauma_nurse'),
    ('Basenji Dad', 'Recovery Nurse', 'white_shirt', 'dog', 'his', 'basenji_dad_recovery_nurse'),
    ('Jack Russell Terrier Mom', 'Case Manager Nurse', 'black_shirt', 'dog', 'her', 'jack_russell_terrier_mom_case_manager_nurse'),
    ('West Highland Terrier Dad', 'Nurse Educator', 'white_shirt', 'dog', 'his', 'west_highland_terrier_dad_nurse_educator'),
    ('Scottish Terrier Mom', 'Wound Care Nurse', 'black_shirt', 'dog', 'her', 'scottish_terrier_mom_wound_care_nurse'),
    ('Bull Terrier Dad', 'Telemetry Nurse', 'white_shirt', 'dog', 'his', 'bull_terrier_dad_telemetry_nurse'),
    ('Mastiff Mom', 'Infusion Nurse', 'black_shirt', 'dog', 'her', 'mastiff_mom_infusion_nurse'),
    ('Russian Blue Cat Mom', 'Telemetry Nurse', 'black_shirt', 'cat', 'her', 'russian_blue_cat_mom_telemetry_nurse'),
    ('Scottish Fold Cat Mom', 'Infusion Nurse', 'white_shirt', 'cat', 'her', 'scottish_fold_cat_mom_infusion_nurse'),
]
